In [1]:
import numpy as np

### NumPy arrays

In [156]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [157]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [158]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [159]:
array = np.repeat(0.0, 10) 
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [160]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [161]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

In [162]:
el = array[1]
print(el)

0.0


In [164]:
array[[4, 2, 0]]

array([1., 1., 0.])

In [147]:
array[1] = 1
print(array)

[0. 1. 1. 1. 1.]


In [148]:
elements = [1, 2, 3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

In [149]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [12]:
zeros[0] = 300
zeros

array([44,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8)

In [13]:
zeros[0] = 300
print(zeros[0])

44


In [14]:
300 % 256

44

In [15]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


### Multi-dimensional NumPy arrays

In [16]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [17]:
print(zeros.shape)

(5, 2)


In [151]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [152]:
print(numbers[0, 1])

2


In [248]:
numbers[0, 1] = 10

In [249]:
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [153]:
numbers[0]

array([1, 2, 3])

In [154]:
numbers[:, 1]

array([2, 5, 8])

In [250]:
numbers[1] = [1, 1, 1]

In [251]:
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [253]:
numbers[:, 2] = [9, 9, 9]

In [254]:
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

### Randomly generated arrays


In [22]:
np.random.rand(5, 2)

array([[0.85889433, 0.1635952 ],
       [0.20812403, 0.37526748],
       [0.79267925, 0.53845298],
       [0.7734247 , 0.72291499],
       [0.15826486, 0.76933125]])

In [23]:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [24]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [29]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

In [30]:
rng * 2

array([0, 2, 4, 6, 8])

In [36]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

In [37]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [39]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [40]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

In [41]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

In [28]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [103]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [101]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

In [106]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [107]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [108]:
np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

In [43]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [45]:
result = pred >= 0.5
result

array([False, False,  True])

In [111]:
np.random.seed(2)


In [112]:
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [113]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [114]:
pred1 >= pred2

array([ True, False,  True])

In [115]:
np.random.seed(2)

In [116]:
pred1 = np.random.rand(3) >= 0.3
pred1

array([ True, False,  True])

In [117]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True,  True, False])

In [120]:
pred1 & pred2

array([ True, False, False])

In [121]:
pred1 | pred2

array([ True,  True,  True])

### Summarizing operations

In [122]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [123]:
pred_sum

1.02

In [98]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


In [125]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [126]:
matrix.max()

0.62

In [127]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [128]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [113]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

## Sort

In [129]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [130]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [131]:
pred

array([0.44, 0.03, 0.55, 0.44])

In [132]:
pred.sort()

In [135]:
pred

array([0.03, 0.44, 0.44, 0.55])

In [136]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [137]:
idx = pred.argsort()

In [138]:
idx

array([1, 0, 3, 2])

In [126]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

## Reshaping

In [197]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [198]:
rng.shape

(12,)

In [199]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [200]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [201]:
rng.reshape(4, 4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [213]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [214]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [215]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [216]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [218]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [230]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [221]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [222]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [231]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [226]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [229]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [228]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

## Slicing

In [233]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [234]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [240]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [238]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [241]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [242]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [247]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [246]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

## Linear Algebra

### Multiplication

### Inverse

In [277]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [278]:
Ainv = np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [279]:
A.dot(Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [286]:
B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])

np.linalg.inv(B)

LinAlgError: Singular matrix

In [281]:
b = np.array([1, 2, 3])

In [283]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [284]:
A.dot(x)

array([1., 2., 3.])