## Session 1 Homework

*Course:* Machine Learning Bookcamp
<br>
*Course Author:* Alexey Grigorev
<br>
*Date:* 13.09.2021
<br>
*Submitted by:* Ashish Soni

### Set up the environment

You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from [07-environment.md](06-environment.md).


In [16]:
#Setup

import numpy as np
import pandas as pd

### Question 1

What's the version of NumPy that you installed? 

You can get the version information using the `__version__` field:


In [17]:
print('Numpy Version:',np.__version__)

Numpy Version: 1.20.2



### Question 2

What's the version of Pandas? 



In [18]:
print('Pandas Version:', pd.__version__)

Pandas Version: 1.2.4


### Getting the data 
For this homework, we'll use the same dataset as for the next session - the car price dataset.

Download it from [here](https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv).

You can do it with wget:

```bash
wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
```

Or just open it with your browser and click "Save as...".



Now read it with Pandas. 


In [19]:
car_data = pd.read_csv('D:/Github/mlbookcamp-code/course-zoomcamp/01-intro/data.csv')

car_data.head()


Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]



### Question 3

What's the average price of BMW cars in the dataset?



In [24]:
bmw_cars = car_data[car_data['Make'] == 'BMW']

bmw_cars_avg_price = np.mean(bmw_cars['MSRP'])

print('Average Price of BMW cars is:', bmw_cars_avg_price)

Average Price of BMW cars is: 61546.76347305389



### Question 4

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?



In [38]:
cars_2015 = car_data[car_data['Year'] >= 2015]

cars_2015_engine_null = cars_2015['Engine HP']

print('Number of missing values for Engine HP:', cars_2015_engine_null.isnull().sum())

Number of missing values for Engine HP: 51



### Question 5

* Calculate the average "Engine HP" in the dataset. 
* Use the `fillna` method and to fill the missing values in "Engine HP" with the mean value from the previous step. 
* Now, calcualte the average of "Engine HP" again.
* Has it changed? 

Round both means before answering this questions. You can use the `round` function for that:


In [52]:
engine_hp = car_data['Engine HP']

mean_hp_before = np.mean(engine_hp)

mean Engine HP before filling missing values 249
mean Engine HP after: 249
So No changes


In [ ]:
car_data_engine_hp = car_data['Engine HP']
new_engine_hp = car_data_engine_hp.fillna(mean_hp_before)

In [ ]:
mean_hp_after = np.mean(new_engine_hp)

print('mean Engine HP before filling missing values', round(mean_hp_before))

print('mean Engine HP after:', round(mean_hp_after))

print('So No changes')



### Question 6

* Select all the "Rolls-Royce" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
* Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 7 rows).
* Get the underlying NumPy array. Let's call it `X`.
* Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
* Invert `XTX`.
* What's the sum of all the elements of the result?

Hint: if the result is negative, re-read the task one more time


In [58]:
rolls_royce_cars = car_data[car_data['Make'] == 'Rolls-Royce']

new_dataset = rolls_royce_cars[['Engine HP', 'Engine Cylinders', 'highway MPG']]

new_dataset.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [96]:
new_unique_data = new_dataset.drop_duplicates()
print(new_unique_data)


       Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21


array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [ ]:
x = new_unique_data.values
x

In [110]:
xt = x.T

xtx = np.matmul(xt,x)
xtx

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [111]:
inverted_xtx = np.linalg.inv(xtx)
inverted_xtx

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [112]:
np.sum(inverted_xtx)

0.032212320677486125



### Questions 7 

* Create an array `y` with values `[1000, 1100, 900, 1200, 1000, 850, 1300]`.
* Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
* What's the value of the first element of `w`?.


In [124]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [122]:
new_x = np.matmul(inverted_xtx,xt)

w = np.matmul(new_x,y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [123]:
first_element = w[0]
print('first element of w is:', first_element)

first element of w is: 0.19989598183188972
