In [1]:
import numpy as np
import pandas as pd

### 1) What's the version of NumPy that you installed?

In [3]:
np.__version__

'1.21.5'

### 2) What's the version of Pandas?

In [4]:
pd.__version__

'1.4.2'

***
Importing data


In [17]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv -O hw-1.csv

--2022-06-08 15:23:46--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘hw-1.csv’

hw-1.csv            100%[===================>]   1.41M  --.-KB/s    in 0.07s   

2022-06-08 15:23:46 (20.3 MB/s) - ‘hw-1.csv’ saved [1475504/1475504]



In [18]:
df = pd.read_csv('hw-1.csv')

In [19]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### 3) What's the average price of BMW cars in the dataset?

In [14]:
print('Average price of BMWs in the dataset:','$'+str(round(df[df['Make'] == 'BMW']['MSRP'].mean(),2)))

Average price of BMWs in the dataset: $61546.76


### Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [21]:
print('Number of missing Engine HP values:',df[df['Year']>=2015]['Engine HP'].isna().sum())

Number of missing Engine HP values: 51


### 5a) Calculate the average "Engine HP" in the dataset.

In [26]:
print('Average Engine HP:',df['Engine HP'].mean())

Average Engine HP: 249.38607007176


### 5b) Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

In [29]:
average_engine_hp = df['Engine HP'].mean()
print(average_engine_hp)

249.38607007176


### 5c) Now, calcualte the average of "Engine HP" again.

In [30]:
df['Engine HP'] = df['Engine HP'].fillna(average_engine_hp)

### 5d) Has it changed?

In [33]:
print('Average Engine HP Change after filling average in for NA values:',df['Engine HP'].mean() != average_engine_hp)

Average Engine HP Change after filling average in for NA values: False


### 6a) Select all the "Rolls-Royce" cars from the dataset.

In [36]:
rolls_royce_df = df[df['Make'] == 'Rolls-Royce']
rolls_royce_df

Make                   Model  Year             Engine Fuel Type  \
2921   Rolls-Royce                Corniche  2001  premium unleaded (required)   
3505   Rolls-Royce                    Dawn  2016  premium unleaded (required)   
5275   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5276   Rolls-Royce         Ghost Series II  2015  premium unleaded (required)   
5277   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5278   Rolls-Royce         Ghost Series II  2016  premium unleaded (required)   
5279   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5280   Rolls-Royce                   Ghost  2012  premium unleaded (required)   
5281   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5282   Rolls-Royce                   Ghost  2013  premium unleaded (required)   
5283   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
5284   Rolls-Royce                   Ghost  2014  premium unleaded (required)   
7443   Rolls-Royce               Park Ward  2001  premium unleaded (required)   
7444   Rolls-Royce               Park Ward  2002  premium unleaded (required)   
7553   Rolls-Royce           Phantom Coupe  2014  premium unleaded (required)   
7554   Rolls-Royce           Phantom Coupe  2015  premium unleaded (required)   
7555   Rolls-Royce           Phantom Coupe  2016  premium unleaded (required)   
7556   Rolls-Royce  Phantom Drophead Coupe  2014  premium unleaded (required)   
7557   Rolls-Royce  Phantom Drophead Coupe  2015  premium unleaded (required)   
7558   Rolls-Royce  Phantom Drophead Coupe  2016  premium unleaded (required)   
7559   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7560   Rolls-Royce                 Phantom  2014  premium unleaded (required)   
7561   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7562   Rolls-Royce                 Phantom  2015  premium unleaded (required)   
7563   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
7564   Rolls-Royce                 Phantom  2016  premium unleaded (required)   
9431   Rolls-Royce           Silver Seraph  2001  premium unleaded (required)   
9432   Rolls-Royce           Silver Seraph  2002  premium unleaded (required)   
11448  Rolls-Royce                  Wraith  2014  premium unleaded (required)   
11449  Rolls-Royce                  Wraith  2015  premium unleaded (required)   
11450  Rolls-Royce                  Wraith  2016  premium unleaded (required)   

       Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921       325.0               8.0         AUTOMATIC  rear wheel drive   
3505       563.0              12.0         AUTOMATIC  rear wheel drive   
5275       563.0              12.0         AUTOMATIC  rear wheel drive   
5276       563.0              12.0         AUTOMATIC  rear wheel drive   
5277       563.0              12.0         AUTOMATIC  rear wheel drive   
5278       563.0              12.0         AUTOMATIC  rear wheel drive   
5279       563.0              12.0         AUTOMATIC  rear wheel drive   
5280       563.0              12.0         AUTOMATIC  rear wheel drive   
5281       563.0              12.0         AUTOMATIC  rear wheel drive   
5282       563.0              12.0         AUTOMATIC  rear wheel drive   
5283       563.0              12.0         AUTOMATIC  rear wheel drive   
5284       563.0              12.0         AUTOMATIC  rear wheel drive   
7443       322.0              12.0         AUTOMATIC  rear wheel drive   
7444       322.0              12.0         AUTOMATIC  rear wheel drive   
7553       453.0              12.0         AUTOMATIC  rear wheel drive   
7554       453.0              12.0         AUTOMATIC  rear wheel drive   
7555       453.0              12.0         AUTOMATIC  rear wheel drive   
7556       453.0              12.0         AUTOMATIC  rear wheel drive   
7557       453.

### 6b) Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

In [39]:
engine_hp_cyl_hwyMPG = rolls_royce_df[['Engine HP','Engine Cylinders','highway MPG']]

### 6c) Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

In [84]:
engine_hp_cyl_hwyMPG= engine_hp_cyl_hwyMPG.drop_duplicates()

### 6d) Get the underlying NumPy array. Let's call it X.

In [85]:
X = engine_hp_cyl_hwyMPG.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

### 6e) Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [86]:
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

### 6f) Invert XTX.

In [87]:
XTX_inv = np.linalg.inv(XTX)

### 6g) What's the sum of all the elements of the result?

In [89]:
XTX_inv.sum()

0.032212320677486195

### 7a) Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].

In [91]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

### 7b) Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.


In [96]:
w = XTX_inv.dot(X.T).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

### 7c) What's the value of the first element of w?.

In [98]:
w[0]

0.19989598183186175